workspace:
  path: /github.com/elastos

kind: pipeline
name: crc-test

clone:
  depth: 10

volumes:
- name: root
  host:
    path: /data/jepsen

steps:
- name: worker
  image: peterwillcn/drone-kubernetes:0.0.1
  volumes:
  - name: root
    path: /root
  commands:
  - kubectl create -f k8s/crc-system.yml || true
  - sleep 30
  - /pods -ns crc-system

- name: make
  image: golang:1.12
  environment:
    GOPATH: /drone
  commands:
  - git clone --depth 5 -b jepsen https://github.com/elastos/Elastos.ELA.git
  - cd Elastos.ELA
  - glide install
  - make all
  - make dns
  - cp ela ela-cli ela-dns ../

- name: running
  image: peterwillcn/jepsen_control:0.1.2
  volumes:
  - name: root
    path: /root
  commands:
  - ./ela -v
  - eval $(ssh-agent)
  - ssh-add
  - cat /root/crc-system
    # TODO: Clojure injection parameters from /root/{namespace}
  - lein run test --strict-host-key-checking no \
    --concurrency 5 -n 192.168.3.16 -n 192.168.3.12 -n 192.168.3.15 -n 192.168.3.11 -n 192.168.3.14
  when:
    event:
    - push
    - pull_request

- name: teardown
  image: peterwillcn/drone-kubernetes:0.0.1
  volumes:
  - name: root
    path: /root
  commands:
  - kubectl delete -f k8s/crc-system.yml || true
---
workspace:
  path: /github.com/elastos

kind: pipeline
name: database-test

clone:
  depth: 10

volumes:
- name: root
  host:
    path: /data/jepsen

steps:
- name: worker
  image: peterwillcn/drone-kubernetes:0.0.1
  volumes:
  - name: root
    path: /root
  commands:
  - kubectl create -f k8s/database-system.yml || true
  - sleep 120
  - /pods -ns database-system

- name: make
  image: golang:1.12
  environment:
    GOPATH: /drone
  commands:
  - git clone --depth 5 -b jepsen https://github.com/elastos/Elastos.ELA.git
  - cd Elastos.ELA
  - glide install
  - make all
  - make dns
  - cp ela ela-cli ela-dns ../

- name: running
  image: peterwillcn/jepsen_control:0.1.2
  volumes:
  - name: root
    path: /root
  commands:
  - ./ela -v
  - eval $(ssh-agent)
  - ssh-add
  - cat /root/database-system
    # TODO: Clojure injection parameters from /root/{namespace}
  - lein run test --strict-host-key-checking no \
    --concurrency 5 -n 192.168.3.16 -n 192.168.3.12 -n 192.168.3.15 -n 192.168.3.11 -n 192.168.3.14
  when:
    event:
    - push
    - pull_request

- name: teardown
  image: peterwillcn/drone-kubernetes:0.0.1
  volumes:
  - name: root
    path: /root
  commands:
  - kubectl delete -f k8s/database-system.yml || true
